### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by sqp** [linux-man/ezame#4]
Hello, I saw your program referenced in the cairo-dock code as one of the possible menu editors.
Since previous options didn't worked, I tried to install it but it failed to start.

Using Archlinux package: aur/ezame-git 0.6-1 [installed] [1]  <--- yes I'm the only one who installed it ATM.

```
 File "/usr/lib/python3.4/site-packages/ezame/main.py", line 1298, in load_prefs
    self.xdg_data_dirs = os.environ.get("XDG_DATA_DIRS").split(":") + [xdg_data_home] or ("/usr/local/share:/usr/share").split(":")
```

I removed the part before "or", and had to do the same on line 1300 to have the program start (XDG_CONFIG_DIRS).

(those environment vars don't exist on my system)

The GUI seemed to show my menu items but I wasn't able to deactivate them.

So I tried to switch to "menu" mode and got this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ezame/main.py", line 388, in on_Mpreferences_activate
    self.load_menu()
  File "/usr/lib/python3.4/site-packages/ezame/main.py", line 1056, in load_menu
    else: load_freedesktop(self)
  File "/usr/lib/python3.4/site-packages/ezame/main.py", line 1026, in load_freedesktop
    if not os.path.exists(os.path.dirname(self.config_file)): os.mkdir(os.path.dirname(self.config_file))
AttributeError: 'Ezame' object has no attribute 'config_file'
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ezame/main.py", line 91, in gtk_main_quit
    if not os.path.exists(os.path.dirname(self.config_file)): os.mkdir(os.path.dirname(self.config_file))
AttributeError: 'Ezame' object has no attribute 'config_file'
```

**Comment by Photon89** [comment]
Hi, I'm the maintainer of the AUR package. I realize that i for some reason didn't upload the new rev of ezame (or maybe I did but it got lost during the AUR move to git). The essential change is that desktop-file-utils has been added as dependency in the new rev. Could you pleas check if desktop-file-utils is installed on your machine?

**Comment by sqp** [comment]
Hi, yes desktop-file-utils is installed.
extra/desktop-file-utils 0.22-1 [installed]

I don't know python, but this seem that lines I'm having problems with haven't changed.
The crash seem related to os.environ.get on a missing var, or it's further split (lines 1298 and 1300)

https://github.com/linux-man/ezame/blob/master/ezame/main.py#L1298

**Comment by linux-man** [comment]
Thanks for your report. You're right. "XDG_DATA_DIRS" is a freedesktop.org Directory Specification and "should" exist in every linux. A try block will solve the problem. The lack of "config_file" is more worrier. Please, just enter/exit the program (that should be enough to create the config file at ~/.config/ezame) and see if the problem remains.
I'll install arch this weekend (been with debian/ubuntu for too much, I guess).

**Comment by sqp** [comment]
Missing env vars are may be related to the way I started my session (cinnamon without cinnamon)

I'm not sure the spec explicitly says they are mandatory, and it specifies the fallback for each of them:
> If $XDG_DATA_DIRS is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used.
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

Clicking on File > Quit (doesn't close the program):
Traceback (most recent call last):
```
  File "/usr/lib/python3.4/site-packages/ezame/main.py", line 91, in gtk_main_quit
    if not os.path.exists(os.path.dirname(self.config_file)): os.mkdir(os.path.dirname(self.config_file))
AttributeError: 'Ezame' object has no attribute 'config_file'
```

Closing the window outputs the same message, and hangs (not releasing the console).
No file/dir found at $HOME/.config/ezame
(Python 3.4.3)

Thanks for such a quick answer :)

**Comment by linux-man** [comment]
I just installed ezame on Manjaro XFCE. Good news are: it works just fine!
I guess those missing system vars are specific to your system. You really should get some...
Now seriously: I noticed that you already edited main.py, so could you please do it again?
From line 1297 to 1301 change code to:

			xdg_data_home = os.environ.get("XDG_DATA_HOME") or os.path.join(os.path.expanduser("~"), ".local", "share")
			try:
				self.xdg_data_dirs = os.environ.get("XDG_DATA_DIRS").split(":") + [xdg_data_home] or ("/usr/local/share:/usr/share").split(":")
			except:
				self.xdg_data_dirs = [xdg_data_home] or ("/usr/local/share:/usr/share").split(":")
				pass

			xdg_config_home = os.environ.get("XDG_CONFIG_HOME") or os.path.join(os.path.expanduser("~"), ".config")
			try:
				self.xdg_config_dirs = os.environ.get("XDG_CONFIG_DIRS").split(":") + [xdg_config_home] or ["/etc/xdg"]
			except:
				self.xdg_config_dirs = [xdg_config_home] or ["/etc/xdg"]
				pass
				
			self.xdg_data_dirs.reverse()

**Comment by linux-man** [comment]
I uploaded the changes.
Photon89: If you want to update AUR, please note that python-xdg is no longer a dependency.

**Comment by Photon89** [comment]
Updated AUR package, sqp, please test!

**Comment by sqp** [comment]
Hey, I can't test edition ATM, but the program is starting, it's full of icons, and I can switch between apps/menu views. 

Seems to be a good and fast job. My issues are closed, I'll let you know if I have other problems.
Thanks, it was a pleasure.

PS: Is it adviceable to recommand this ppa for cairo-dock users having problems with other menu edition programs (https://launchpad.net/~caldas-lopes/+archive/ubuntu/ppa) ?

**Comment by linux-man** [comment]
It's ezame's official (and only) ppa. And it has more than 1 download! I guess I can recommend it.
