### ISSUE TITLE
Ezame crashes on start

### ISSUE THREAD

**Issue by Photon89** [linux-man/ezame#5]
After a long time I started ezame again and get the following crash:

```
$ ezame 
/usr/lib/python3.6/site-packages/ezame/main.py:7: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GdkPixbuf, Pango
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ezame/desktop.py", line 39, in __init__
    self.content.read([filename])
  File "/usr/lib/python3.6/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1012, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 21: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ezame", line 4, in <module>
    run()
  File "/usr/lib/python3.6/site-packages/ezame/main.py", line 1467, in __init__
    app = Ezame()
  File "/usr/lib/python3.6/site-packages/ezame/main.py", line 1419, in __init__
    self.load_menu()
  File "/usr/lib/python3.6/site-packages/ezame/main.py", line 1055, in load_menu
    elif self.desktop == "Apps": load_apps(self)
  File "/usr/lib/python3.6/site-packages/ezame/main.py", line 940, in load_apps
    Entry, local_icon = self.read_entry(desk_file)
  File "/usr/lib/python3.6/site-packages/ezame/main.py", line 858, in read_entry
    Entry = DE(desk_file[i_local])
  File "/usr/lib/python3.6/site-packages/ezame/desktop.py", line 42, in __init__
    self.faulty_text = df.read()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 21: invalid continuation byte
```

**Comment by linux-man** [comment]
Hello again!
I'm still on python 3.5, and I can't replicate your error.
The chances are:
- There is something new on 3.6 that breaks the code.
- You have a ill-formed desktop file that breaks ezame when loading.

The line where the crash occurs is inside a try block to avoid this kind of issues.
Can you edit some code?
at /usr/lib/python3/dist-packages/ezame/desktop.py could you add at line 39
```
			try:
				print(filename) #this one
				self.content.read([filename])
			except:
```
to find the last file ezame tries to open. That must be the culprit.

I'll look further on how to catch this error.

**Comment by Photon89** [comment]
Unfortunately, it cannot print the file name either... After a long list of filenames which see unproblematic, it gives:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ezame/desktop.py", line 39, in __init__
    print(filename) #this one
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 98-104: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ezame", line 4, in <module>
    run()
  File "/usr/lib/python3.6/site-packages/ezame/main.py", line 1467, in __init__
    app = Ezame()
  File "/usr/lib/python3.6/site-packages/ezame/main.py", line 1419, in __init__
    self.load_menu()
  File "/usr/lib/python3.6/site-packages/ezame/main.py", line 1055, in load_menu
    elif self.desktop == "Apps": load_apps(self)
  File "/usr/lib/python3.6/site-packages/ezame/main.py", line 940, in load_apps
    Entry, local_icon = self.read_entry(desk_file)
  File "/usr/lib/python3.6/site-packages/ezame/main.py", line 858, in read_entry
    Entry = DE(desk_file[i_local])
  File "/usr/lib/python3.6/site-packages/ezame/desktop.py", line 43, in __init__
    self.faulty_text = df.read()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 21: invalid continuation byte
```
But I found the problematic file, `ls -l` reports it like this:

`-rw-r--r-- 1 photon users 328 11. Jul 2016  ''$'\323\344\340\353\350\362\374'' '$'\350\343\360\363''.desktop'`

and Thunar, the file manager, shows question marks in the name.

It isn't important and I can just delete it (it isn't displayed in the menu anyway). But of course it would be nice, if Ezame would somehow skip such files and not crash. 😃

**Comment by linux-man** [comment]
I think this changes will catch all bad file names.
It also corrects a long time bug on "categories" and "show only" selection.
Please test.
[main.py.zip](https://github.com/linux-man/ezame/files/916250/main.py.zip)

**Comment by Photon89** [comment]
Yep, works now, thanks a lot!

**Comment by Photon89** [comment]
However, the same thing still happens when switching to the directory mode:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ezame/main.py", line 394, in on_Mpreferences_activate
    self.load_menu()
  File "/usr/lib/python3.6/site-packages/ezame/main.py", line 1068, in load_menu
    else: load_freedesktop(self)
  File "/usr/lib/python3.6/site-packages/ezame/main.py", line 1036, in load_freedesktop
    with open (menu_file, "r") as menu: data=menu.read()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 599: invalid continuation byte
```

**Comment by linux-man** [comment]
And now?
[main.py.zip](https://github.com/linux-man/ezame/files/916372/main.py.zip)
You have and outrageous number of bad file names. It almost look like a virus infection... :laughing:
I'm not complaining. It's good for bug catching.

**Comment by Photon89** [comment]
Now everything is fine, thanks again! 👍  Not a virus infection, just some WINE apps, seems like windows programs aren't taking good encoding too serious...

**Comment by linux-man** [comment]
If you're going to update AUR, maybe you could see if [Unreel](https://github.com/linux-man/unreel) is AURable.
## Aurable
### adjective
1. having the ability or capacity to belong to AUR:

**Comment by Photon89** [comment]
I like the neologism. 👍  Could you please give me some hints on how to install and how to use Unreel?

**Comment by linux-man** [comment]
You find a release with binaries, zip, deb, appimage.
Installation is usually on opt. It's an Electron app so it should follow the same rules of an Atom or Skype beta installation.

**Comment by Photon89** [comment]
Ah, I see! Then it should be aurable, I guess, question is just if I can aur it. 😛  I will have a look and report back!

**Comment by Photon89** [comment]
So I'm trying to package it but to be honest I don't understand what to do with the contents of the source archive. I tried to get some inspiration from other electron apps' PKGBUILDs but didn't find any pattern which I could apply to unreel. Need some help here. 😄

**Comment by linux-man** [comment]
You can ignore them. They are already in the binary archives.

**Comment by Photon89** [comment]
You mean, ignore the source archive and use some of the binary archives? But AUR packages should build things from source unless there is no such option.

**Comment by linux-man** [comment]
You're right. Use the source.
https://electron.atom.io/docs/tutorial/application-distribution/
The zip "binaries" were made  by https://github.com/electron-userland/electron-packager

**Comment by Photon89** [comment]
Ok, I think, I almost did it, based on the PKGBUILD for wire-desktop: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wire-desktop Only need to take care of the icon and a .desktop file now but I will finalize it tomorrow.

**Comment by Photon89** [comment]
Done: https://aur.archlinux.org/packages/unreel/ Please check if you can. :)

**Comment by linux-man** [comment]
I can't thank you enough. Maybe I can pay you a :beer: someday.
I'm not using Arch for a while, so I can't check.

**Comment by Photon89** [comment]
No need to thank, thank you for developing the actual software! :)

**Comment by linux-man** [comment]
One last thing:  the dark sorcery of registering unreel with "reel" files (just learned).
You need to copy the icon to /usr/share/icons/hicolor/512x512/mimetypes/application-reel.png
Create /usr/share/mime/packages/unreel.xml with
```
<?xml version="1.0" encoding="utf-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/reel">
     <glob pattern="*.reel"/>
  </mime-type>
</mime-info>
```
add `MimeType=application/reel` to unreel.desktop
ad that's it.

**Comment by Photon89** [comment]
Updated! https://aur.archlinux.org/cgit/aur.git/commit/?h=unreel&id=0c1bd55ce3c8a49c47b5be70f16b11907f2770d8
