### ISSUE TITLE
Permissions seem to be borked - ezame does not launch

### ISSUE THREAD

**Issue by Photon89** [linux-man/ezame#6]
The executable seems to miss the x flag:
```
$ ls -l /usr/bin/ezame
-rw-r--r-- 1 root root 81 30. Aug 07:40 /usr/bin/ezame
```
When trying to launch:
```
ezame
-bash: /usr/bin/ezame: No permission
```

**Comment by linux-man** [comment]
Damn! I hate when this happens!
I hope it's OK now.

**Comment by Photon89** [comment]
Thanks! Could you also update the release tarball?

**Comment by linux-man** [comment]
Done. Sorry about that. I never check because deb build take care of that permission.

**Comment by Photon89** [comment]
Cool, will update the AUR package asap!
